---
version: 2
updates:
- package-ecosystem: docker
  directory: /bankwiz_server
  schedule:
    interval: monthly
    timezone: Europe/Paris
  open-pull-requests-limit: 100
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    timezone: Europe/Paris
  open-pull-requests-limit: 100
