---
name: Main branch CI
permissions:
  contents: read
"on":
  push:
    branches:
    - main
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true
jobs:
  build_push_docker:
    runs-on: ubuntu-latest
    name: Build and push docker image
    permissions:
      packages: write
    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          ghcr.io/jbwittner/action_runner_image:main-latest
          ghcr.io/jbwittner/action_runner_image:main-${{ github.sha }}
